In [2]:
import numpy as np
import pandas as pd

In [3]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [4]:
df = pd.read_csv('covid_toy.csv')

In [5]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [6]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [7]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [9]:
X_train

    age  gender  fever   cough       city
24   13  Female  100.0  Strong    Kolkata
7    20  Female    NaN  Strong     Mumbai
51   11  Female  100.0  Strong    Kolkata
99   10  Female   98.0  Strong    Kolkata
21   73    Male   98.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
34   74    Male  102.0    Mild     Mumbai
10   75  Female    NaN    Mild      Delhi
16   69  Female  103.0    Mild    Kolkata
92   82  Female  102.0  Strong    Kolkata
13   64    Male  102.0    Mild  Bangalore

[80 rows x 5 columns]

In [16]:
X_test

    age  gender  fever   cough       city
23   80  Female   98.0    Mild      Delhi
48   66    Male   99.0  Strong  Bangalore
28   16    Male  104.0    Mild    Kolkata
88    5  Female  100.0    Mild    Kolkata
85   16  Female  103.0    Mild  Bangalore
63   10    Male  100.0    Mild  Bangalore
2    42    Male  101.0    Mild      Delhi
87   47    Male  101.0  Strong  Bangalore
11   65  Female   98.0    Mild     Mumbai
49   44    Male  104.0    Mild     Mumbai
18   64  Female   98.0    Mild  Bangalore
82   24    Male   98.0    Mild    Kolkata
0    60    Male  103.0    Mild    Kolkata
70   68  Female  101.0  Strong      Delhi
41   82    Male    NaN    Mild    Kolkata
26   19  Female  100.0    Mild    Kolkata
3    31  Female   98.0    Mild    Kolkata
47   18  Female  104.0    Mild  Bangalore
61   81  Female   98.0  Strong     Mumbai
94   79    Male    NaN  Strong    Kolkata

**1. Aam Zindagi**'

In [10]:
# adding simple imouter to fever column
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [11]:
X_train_fever

array([[100.        ],
       [100.94444444],
       [100.        ],
       [ 98.        ],
       [ 98.        ],
       [ 98.        ],
       [101.        ],
       [101.        ],
       [100.94444444],
       [100.        ],
       [102.        ],
       [104.        ],
       [ 99.        ],
       [101.        ],
       [101.        ],
       [ 99.        ],
       [ 98.        ],
       [100.94444444],
       [103.        ],
       [101.        ],
       [103.        ],
       [104.        ],
       [ 99.        ],
       [104.        ],
       [102.        ],
       [100.94444444],
       [ 98.        ],
       [104.        ],
       [101.        ],
       [102.        ],
       [100.94444444],
       [101.        ],
       [ 98.        ],
       [100.        ],
       [104.        ],
       [104.        ],
       [ 98.        ],
       [ 99.        ],
       [100.        ],
       [101.        ],
       [ 99.        ],
       [ 99.        ],
       [ 98.        ],
       [102.        ],
       [ 99.        ],
       [100.94444444],
       [100.        ],
       [ 98.        ],
       [102.        ],
       [ 99.        ],
       [100.94444444],
       [104.        ],
       [104.        ],
       [101.        ],
       [103.        ],
       [101.        ],
       [ 98.        ],
       [101.        ],
       [101.        ],
       [104.        ],
       [ 98.        ],
       [102.        ],
       [100.        ],
       [101.        ],
       [101.        ],
       [103.        ],
       [102.        ],
       [100.        ],
       [ 99.        ],
       [100.        ],
       [103.        ],
       [103.        ],
       [104.        ],
       [100.        ],
       [104.        ],
       [102.        ],
       [100.94444444],
       [103.        ],
       [102.        ],
       [102.        ]])

In [12]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [17]:
X_train_cough

array([[1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.]])

In [13]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [15]:
# Extracting age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

#also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [18]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

**Menton Zindagi**

In [19]:
from sklearn.compose import ColumnTransformer

In [21]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [22]:
transformer.fit_transform(X_train).shape

(80, 7)

In [23]:
transformer.transform(X_test).shape

(20, 7)